-- FAR Website Manager expansion
alter table public.far_custom_pages add column if not exists navigation_location text not null default 'community';
alter table public.far_custom_pages add column if not exists navigation_label text;
alter table public.far_custom_pages drop constraint if exists far_custom_pages_navigation_location_check;
alter table public.far_custom_pages add constraint far_custom_pages_navigation_location_check check (navigation_location in ('hidden','main','news','community','on_air'));

create table if not exists public.far_podcasts (
 id bigint generated by default as identity primary key,title text not null,description text default '',artwork_url text default '',audio_url text default '',link_url text default '',presenter text default '',published_at timestamptz,enabled boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.far_listen_platforms (
 id bigint generated by default as identity primary key,title text not null,description text default '',button_text text default '',button_url text default '',icon text default '',enabled boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.far_public_file_sections (
 id bigint generated by default as identity primary key,heading text not null,content text default '',enabled boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.far_team (
 id bigint generated by default as identity primary key,name text not null,role_title text default '',bio text default '',image_url text default '',show_name text default '',enabled boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);

alter table public.far_podcasts enable row level security;
alter table public.far_listen_platforms enable row level security;
alter table public.far_public_file_sections enable row level security;
alter table public.far_team enable row level security;

drop policy if exists "Public reads published FAR podcasts" on public.far_podcasts;
create policy "Public reads published FAR podcasts" on public.far_podcasts for select to anon,authenticated using (enabled=true);
drop policy if exists "FAR podcast staff manage podcasts" on public.far_podcasts;
create policy "FAR podcast staff manage podcasts" on public.far_podcasts for all to authenticated using (public.far_has_permission('podcasts')) with check (public.far_has_permission('podcasts'));

drop policy if exists "Public reads FAR listen platforms" on public.far_listen_platforms;
create policy "Public reads FAR listen platforms" on public.far_listen_platforms for select to anon,authenticated using (enabled=true);
drop policy if exists "FAR listen staff manage platforms" on public.far_listen_platforms;
create policy "FAR listen staff manage platforms" on public.far_listen_platforms for all to authenticated using (public.far_has_permission('listen_platforms')) with check (public.far_has_permission('listen_platforms'));

drop policy if exists "Public reads FAR public file" on public.far_public_file_sections;
create policy "Public reads FAR public file" on public.far_public_file_sections for select to anon,authenticated using (enabled=true);
drop policy if exists "FAR public file staff manage" on public.far_public_file_sections;
create policy "FAR public file staff manage" on public.far_public_file_sections for all to authenticated using (public.far_has_permission('public_file')) with check (public.far_has_permission('public_file'));

drop policy if exists "Public reads FAR team" on public.far_team;
create policy "Public reads FAR team" on public.far_team for select to anon,authenticated using (enabled=true);
drop policy if exists "FAR team staff manage" on public.far_team;
create policy "FAR team staff manage" on public.far_team for all to authenticated using (public.far_has_permission('presenters')) with check (public.far_has_permission('presenters'));

insert into public.far_listen_platforms(title,description,button_text,button_url,sort_order)
select * from (values
 ('FAR App','Install the Fenland Angels Radio web app on a supported phone, tablet or computer.','Open the FAR App','app/',10),
 ('Website','Listen directly from fenlandangelsradio.co.uk using the live player.','Listen on the website','index.html',20),
 ('In the Car','Open FAR on your phone and connect to your car audio using Bluetooth or your normal phone audio connection.','','',30),
 ('Smart Speakers','Smart-speaker listening options will be added here when available.','','',40)
) v(title,description,button_text,button_url,sort_order)
where not exists(select 1 from public.far_listen_platforms);

-- Allow relevant modules to upload CMS media.
drop policy if exists "FAR authorised staff can upload CMS media" on storage.objects;
drop policy if exists "FAR authorised staff can update CMS media" on storage.objects;
drop policy if exists "FAR authorised staff can delete CMS media" on storage.objects;
create policy "FAR authorised staff can upload CMS media" on storage.objects for insert to authenticated with check(bucket_id='far-cms-media' and (public.far_has_permission('pages') or public.far_has_permission('website_content') or public.far_has_permission('podcasts') or public.far_has_permission('presenters') or public.far_has_permission('listen_platforms') or public.far_has_permission('public_file')));
create policy "FAR authorised staff can update CMS media" on storage.objects for update to authenticated using(bucket_id='far-cms-media' and (public.far_has_permission('pages') or public.far_has_permission('website_content') or public.far_has_permission('podcasts') or public.far_has_permission('presenters') or public.far_has_permission('listen_platforms') or public.far_has_permission('public_file'))) with check(bucket_id='far-cms-media');
create policy "FAR authorised staff can delete CMS media" on storage.objects for delete to authenticated using(bucket_id='far-cms-media' and (public.far_has_permission('pages') or public.far_has_permission('website_content') or public.far_has_permission('podcasts') or public.far_has_permission('presenters') or public.far_has_permission('listen_platforms') or public.far_has_permission('public_file')));
