-- FAR WEBSITE MANAGER / NAVIGATION RECOVERY
-- Run once in Supabase SQL Editor.

alter table public.far_custom_pages
  add column if not exists navigation_label text;

alter table public.far_custom_pages
  add column if not exists navigation_location text not null default 'community';

alter table public.far_custom_pages
  add column if not exists sort_order integer not null default 0;

create table if not exists public.far_podcasts(
  id bigint generated by default as identity primary key,
  title text not null default '',
  presenter text,
  description text,
  artwork_url text,
  audio_url text,
  link_url text,
  published_at timestamptz,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.far_listen_platforms(
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text,
  icon text,
  button_text text,
  button_url text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.far_public_file_sections(
  id bigint generated by default as identity primary key,
  heading text not null default '',
  content text not null default '',
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.far_team(
  id bigint generated by default as identity primary key,
  name text not null default '',
  role_title text,
  show_name text,
  bio text,
  image_url text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.far_navigation_items(
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null,
  location text not null check(location in('main','news','community','on_air')),
  sort_order integer not null default 0,
  enabled boolean not null default true,
  system_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.far_podcasts enable row level security;
alter table public.far_listen_platforms enable row level security;
alter table public.far_public_file_sections enable row level security;
alter table public.far_team enable row level security;
alter table public.far_navigation_items enable row level security;

drop policy if exists "Public read enabled podcasts" on public.far_podcasts;
create policy "Public read enabled podcasts"
on public.far_podcasts for select to anon,authenticated
using(enabled=true);

drop policy if exists "Public read enabled listen platforms" on public.far_listen_platforms;
create policy "Public read enabled listen platforms"
on public.far_listen_platforms for select to anon,authenticated
using(enabled=true);

drop policy if exists "Public read enabled public file sections" on public.far_public_file_sections;
create policy "Public read enabled public file sections"
on public.far_public_file_sections for select to anon,authenticated
using(enabled=true);

drop policy if exists "Public read enabled team" on public.far_team;
create policy "Public read enabled team"
on public.far_team for select to anon,authenticated
using(enabled=true);

drop policy if exists "Public read enabled FAR navigation" on public.far_navigation_items;
create policy "Public read enabled FAR navigation"
on public.far_navigation_items for select to anon,authenticated
using(enabled=true);

drop policy if exists "FAR authorised staff manage podcasts" on public.far_podcasts;
create policy "FAR authorised staff manage podcasts"
on public.far_podcasts for all to authenticated
using(public.far_has_permission('podcasts'))
with check(public.far_has_permission('podcasts'));

drop policy if exists "FAR authorised staff manage listen platforms" on public.far_listen_platforms;
create policy "FAR authorised staff manage listen platforms"
on public.far_listen_platforms for all to authenticated
using(public.far_has_permission('listen_platforms'))
with check(public.far_has_permission('listen_platforms'));

drop policy if exists "FAR authorised staff manage public file" on public.far_public_file_sections;
create policy "FAR authorised staff manage public file"
on public.far_public_file_sections for all to authenticated
using(public.far_has_permission('public_file'))
with check(public.far_has_permission('public_file'));

drop policy if exists "FAR authorised staff manage team" on public.far_team;
create policy "FAR authorised staff manage team"
on public.far_team for all to authenticated
using(public.far_has_permission('presenters'))
with check(public.far_has_permission('presenters'));

drop policy if exists "FAR authorised staff manage navigation" on public.far_navigation_items;
create policy "FAR authorised staff manage navigation"
on public.far_navigation_items for all to authenticated
using(public.far_has_permission('navigation'))
with check(public.far_has_permission('navigation'));

insert into public.far_navigation_items(label,href,location,sort_order,system_key)
values
('News','news.html','news',10,'news'),
('Weather','weather.html','news',20,'weather'),
('Events','events.html','community',10,'events'),
('Podcasts','podcasts.html','community',20,'podcasts'),
('Other Ways to Listen','other-ways-to-listen.html','on_air',10,'listen'),
('Schedule','schedule.html','on_air',20,'schedule'),
('Public File','public-file.html','on_air',30,'public'),
('Presenters & Team','team.html','on_air',40,'team'),
('Vouchers','vouchers.html','main',10,'vouchers')
on conflict(system_key) do nothing;
