-- FAR Audience Analytics - run once in the existing FAR Supabase project.
create table if not exists public.far_audience_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in (
    'website_visit','app_open','app_install',
    'listen_start','listen_heartbeat','listen_stop'
  )),
  device_id text not null,
  session_id text not null,
  source text not null check (source in ('website','pwa')),
  page text,
  listen_session_id text,
  duration_seconds integer
);

create index if not exists far_audience_events_created_idx
  on public.far_audience_events(created_at desc);
create index if not exists far_audience_events_device_idx
  on public.far_audience_events(device_id);
create index if not exists far_audience_events_listen_idx
  on public.far_audience_events(listen_session_id, created_at desc);

alter table public.far_audience_events enable row level security;

drop policy if exists "public can add FAR audience events" on public.far_audience_events;
create policy "public can add FAR audience events"
on public.far_audience_events for insert
to anon, authenticated
with check (
  length(device_id) between 3 and 100
  and length(session_id) between 3 and 100
  and source in ('website','pwa')
);

-- Admin dashboard reads through authenticated FAR admin accounts.
drop policy if exists "authenticated can read FAR audience events" on public.far_audience_events;
create policy "authenticated can read FAR audience events"
on public.far_audience_events for select
to authenticated
using (true);

comment on table public.far_audience_events is
'Anonymous first-party FAR website/PWA usage, installs and listening events. No names/emails stored.';
