-- FAR Website CMS - custom pages
create table if not exists public.far_custom_pages (
 id bigint generated by default as identity primary key,
 slug text not null unique,
 title text not null,
 eyebrow text not null default '',
 summary text not null default '',
 body text not null default '',
 hero_image text,
 button_text text,
 button_url text,
 published boolean not null default true,
 show_in_navigation boolean not null default false,
 sort_order integer not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.far_custom_pages enable row level security;
drop policy if exists "public can read published FAR pages" on public.far_custom_pages;
create policy "public can read published FAR pages" on public.far_custom_pages for select to anon,authenticated using (published=true);
drop policy if exists "FAR admins can manage custom pages" on public.far_custom_pages;
create policy "FAR admins can manage custom pages" on public.far_custom_pages for all to authenticated
using (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')))
with check (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')));
