create table if not exists public.far_navigation_items(
 id bigint generated by default as identity primary key,
 label text not null,
 href text not null,
 location text not null check(location in('main','news','community','on_air')),
 sort_order integer not null default 0,
 enabled boolean not null default true,
 system_key text unique,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.far_navigation_items enable row level security;
drop policy if exists "Public read enabled FAR navigation" on public.far_navigation_items;
create policy "Public read enabled FAR navigation" on public.far_navigation_items for select to anon,authenticated using(enabled=true);
drop policy if exists "FAR authorised staff manage navigation" on public.far_navigation_items;
create policy "FAR authorised staff manage navigation" on public.far_navigation_items for all to authenticated using(public.far_has_permission('navigation')) with check(public.far_has_permission('navigation'));

insert into public.far_navigation_items(label,href,location,sort_order,system_key)
values
('News','news.html','news',10,'news'),
('Weather','weather.html','news',20,'weather'),
('Events','events.html','community',10,'events'),
('Podcasts','podcasts.html','community',20,'podcasts'),
('Other Ways to Listen','other-ways-to-listen.html','on_air',10,'listen'),
('Schedule','schedule.html','on_air',20,'schedule'),
('Public File','public-file.html','on_air',30,'public'),
('Presenters & Team','team.html','on_air',40,'team'),
('Vouchers','vouchers.html','main',10,'vouchers')
on conflict(system_key) do nothing;
