-- FAR Website CMS foundation
create table if not exists public.far_schedule (
  id bigint generated by default as identity primary key,
  day_group text not null check (day_group in ('weekday','saturday','sunday')),
  sort_order integer not null default 0,
  start_time time not null,
  end_time time not null,
  show_name text not null,
  presenter text,
  strapline text,
  description text,
  image text,
  featured boolean not null default false,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
create index if not exists far_schedule_day_order_idx on public.far_schedule(day_group,sort_order);
alter table public.far_schedule enable row level security;
drop policy if exists "public can read FAR schedule" on public.far_schedule;
create policy "public can read FAR schedule" on public.far_schedule for select to anon,authenticated using (active=true);
drop policy if exists "FAR admins can manage schedule" on public.far_schedule;
create policy "FAR admins can manage schedule" on public.far_schedule for all to authenticated
using (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and (lower(coalesce(a.role,'')) in ('owner','deputy_manager') or coalesce(a.permissions,'[]'::jsonb) ? 'schedule')))
with check (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and (lower(coalesce(a.role,'')) in ('owner','deputy_manager') or coalesce(a.permissions,'[]'::jsonb) ? 'schedule')));

insert into public.far_schedule(day_group,sort_order,start_time,end_time,show_name,presenter,strapline,description,image,featured)
select * from (values
('weekday',10,'01:00'::time,'04:00'::time,'Overnight Classical',null,'Relax • Unwind • Sleep','Calmer classical music through the early hours.','fenland-angels-radio-logo.jpg',false),
('weekday',20,'04:00','07:00','Early Morning',null,'A gentle start to your day','Easy music to start the day.','fenland-angels-radio-logo.jpg',false),
('weekday',30,'07:00','10:00','Breakfast with Private Major','Private Major','Breakfast across the Fens','Music, local information and breakfast features.','breakfast-private-major.png',true),
('weekday',40,'10:00','16:00','FAR Daytime',null,'Music through the day','Independent and royalty-free music through the day.','fenland-angels-radio-logo.jpg',false),
('weekday',50,'16:00','18:00','Drive Time with Nick','Nick Sheehan','Driving you home with the best music','Drive Time across the Fens.','NICKSHEEHAN-DRIVETIME.png',true),
('weekday',60,'18:00','22:00','FAR Evening',null,'Your evening soundtrack','Your evening soundtrack from across the Fens.','fenland-angels-radio-logo.jpg',false),
('weekday',70,'22:00','01:00','Late Night',null,'Music to get you through the night','Late-night music on Fenland Angels Radio.','fenland-angels-radio-logo.jpg',false),
('saturday',10,'01:00','04:00','Overnight Classical',null,'Relax • Unwind • Sleep','Calmer classical music through the early hours.','fenland-angels-radio-logo.jpg',false),
('saturday',20,'04:00','07:00','Early Morning',null,'A gentle start to your day','Easy music to start the weekend.','fenland-angels-radio-logo.jpg',false),
('saturday',30,'07:00','10:00','Weekend Breakfast',null,'Great music to start your weekend','Weekend breakfast music on FAR.','fenland-angels-radio-logo.jpg',false),
('saturday',40,'10:00','20:00','Weekend Daytime',null,'Feel-good weekend music','Music through Saturday daytime.','fenland-angels-radio-logo.jpg',false),
('saturday',50,'20:00','22:00','Fenland Angels Radio Soundsystem Party','DJ InfinitI','Saturday night dance','High-energy dance music, requests and specialist electronic sounds.','Soundsystem-party-dj-InfinitI.png',true),
('saturday',60,'22:00','01:00','Late Night',null,'Late night dance','Late-night weekend music.','fenland-angels-radio-logo.jpg',false),
('sunday',10,'01:00','04:00','Overnight Classical',null,'Relax • Unwind • Sleep','Calmer classical music through the early hours.','fenland-angels-radio-logo.jpg',false),
('sunday',20,'04:00','07:00','Early Morning',null,'A gentle start to your day','Easy music to begin Sunday.','fenland-angels-radio-logo.jpg',false),
('sunday',30,'07:00','10:00','Sunday Breakfast',null,'A relaxing start to Sunday','Sunday breakfast music on FAR.','fenland-angels-radio-logo.jpg',false),
('sunday',40,'10:00','22:00','Sunday Daytime & Evening',null,'Music for your Sunday','Sunday music across the Fens.','fenland-angels-radio-logo.jpg',false),
('sunday',50,'22:00','01:00','Late Night',null,'Music to get you through the night','Late-night music on FAR.','fenland-angels-radio-logo.jpg',false)
) v(day_group,sort_order,start_time,end_time,show_name,presenter,strapline,description,image,featured)
where not exists(select 1 from public.far_schedule);