create table if not exists public.far_icecast_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  listeners integer not null check (listeners >= 0),
  mount text not null default '/stream',
  stream_online boolean not null default true
);

create index if not exists far_icecast_snapshots_created_at_idx
  on public.far_icecast_snapshots (created_at desc);

alter table public.far_icecast_snapshots enable row level security;

drop policy if exists "allow anonymous icecast snapshot inserts" on public.far_icecast_snapshots;
create policy "allow anonymous icecast snapshot inserts"
on public.far_icecast_snapshots for insert
to anon, authenticated
with check (listeners >= 0 and listeners <= 100000);

drop policy if exists "allow authenticated icecast snapshot reads" on public.far_icecast_snapshots;
create policy "allow authenticated icecast snapshot reads"
on public.far_icecast_snapshots for select
to authenticated
using (true);
