-- FAR CMS page section/block builder
create table if not exists public.far_page_blocks (
 id bigint generated by default as identity primary key,
 page_id bigint not null references public.far_custom_pages(id) on delete cascade,
 block_type text not null check (block_type in ('heading','text','image','button','contact','location','dates','links','callout')),
 heading text not null default '',
 content text not null default '',
 image_url text,
 button_text text,
 button_url text,
 extra jsonb not null default '{}'::jsonb,
 enabled boolean not null default true,
 sort_order integer not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists far_page_blocks_page_order_idx on public.far_page_blocks(page_id,sort_order,id);
alter table public.far_page_blocks enable row level security;
drop policy if exists "Public read published FAR page blocks" on public.far_page_blocks;
create policy "Public read published FAR page blocks" on public.far_page_blocks for select to anon,authenticated
using(enabled=true and exists(select 1 from public.far_custom_pages p where p.id=page_id and p.published=true));
drop policy if exists "FAR admins manage page blocks" on public.far_page_blocks;
create policy "FAR admins manage page blocks" on public.far_page_blocks for all to authenticated
using(exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')))
with check(exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')));
