-- FAR Website CMS - editable public content
create table if not exists public.far_site_content (
  content_key text primary key,
  section text not null default 'general',
  label text not null,
  value text not null default '',
  value_type text not null default 'text' check (value_type in ('text','textarea','url','email','phone','number')),
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);
alter table public.far_site_content enable row level security;
drop policy if exists "public can read FAR site content" on public.far_site_content;
create policy "public can read FAR site content" on public.far_site_content for select to anon,authenticated using (true);
drop policy if exists "FAR admins can manage site content" on public.far_site_content;
create policy "FAR admins can manage site content" on public.far_site_content for all to authenticated
using (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')))
with check (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')));

insert into public.far_site_content(content_key,section,label,value,value_type,sort_order) values
('station_tagline','Station','Station tagline','The Sound of the Fens','text',10),
('station_identity','Station','Station identity','Independent music radio community','text',20),
('contact_email','Station','Contact email','fenlandangelsradio@gmail.com','email',30),
('contact_phone','Station','Contact phone','07401 152538','phone',40),
('homepage_about_title','Homepage','About heading','Independent Music Radio Community','text',10),
('homepage_about_text','Homepage','About text','Fenland Angels Radio is an independent 24/7 internet radio station serving communities across the Fens.','textarea',20),
('recruitment_notice','Homepage','Recruitment notice','We are looking for presenters, DJs and people to join the FAR station team.','textarea',30),
('voucher_status','Vouchers','Voucher status','Coming Soon','text',10),
('voucher_intro','Vouchers','Voucher introduction','The FAR Voucher Shop is coming soon. Check back here for voucher launches, availability and special offers from Fenland Angels Radio.','textarea',20),
('voucher_shop_url','Vouchers','Voucher shop URL','https://fenland-angels-radio.sumupstore.com/','url',30),
('advert_intro','Advertising','Advertising introduction','Affordable radio advertising for local businesses, organisations and community groups.','textarea',10),
('advert_store_url','Advertising','Advertising shop URL','https://fenland-angels-radio.sumupstore.com/','url',20),
('sponsor_notice','Advertising','Sponsorship text','Programme and station sponsorship is arranged directly with Fenland Angels Radio.','textarea',30)
on conflict (content_key) do nothing;

create table if not exists public.far_ad_packages (
 id bigint generated by default as identity primary key,
 sort_order integer not null default 0,
 name text not null,
 price numeric(10,2) not null default 0,
 plays_per_day integer not null default 0,
 description text not null default '',
 includes text not null default '',
 buy_url text,
 active boolean not null default true,
 updated_at timestamptz not null default now()
);
alter table public.far_ad_packages enable row level security;
drop policy if exists "public can read FAR ad packages" on public.far_ad_packages;
create policy "public can read FAR ad packages" on public.far_ad_packages for select to anon,authenticated using (active=true);
drop policy if exists "FAR admins can manage ad packages" on public.far_ad_packages;
create policy "FAR admins can manage ad packages" on public.far_ad_packages for all to authenticated
using (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')))
with check (exists(select 1 from public.far_admins a where a.user_id=auth.uid() and lower(coalesce(a.role,'')) in ('owner','deputy_manager')));

insert into public.far_ad_packages(sort_order,name,price,plays_per_day,description,includes,buy_url) select * from (values
(10,'FAR Starter',25.00,2,'Entry-level local radio advertising.','2 plays per day','https://fenland-angels-radio.sumupstore.com/'),
(20,'FAR Local',45.00,4,'More regular exposure across the FAR schedule.','4 plays per day','https://fenland-angels-radio.sumupstore.com/'),
(30,'FAR Plus',65.00,6,'Increased frequency across Fenland Angels Radio.','6 plays per day','https://fenland-angels-radio.sumupstore.com/'),
(40,'FAR Prime',85.00,8,'Includes rotation during Breakfast and Drive Time.','8 plays per day including Breakfast & Drive','https://fenland-angels-radio.sumupstore.com/'),
(50,'FAR Sponsor',100.00,12,'High-frequency campaign with regular programme mentions.','12 plays per day + regular programme mentions','https://fenland-angels-radio.sumupstore.com/')
) v(sort_order,name,price,plays_per_day,description,includes,buy_url)
where not exists(select 1 from public.far_ad_packages);
